version: "3.4"

services:
  gamifying-tasks:
    image: gamifyingtasks # Assuming you built the image with the updated Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - GOOGLE_APPLICATION_CREDENTIALS=/gcp/creds.json
    volumes:
      - "$HOME/.config/gcloud/application_default_credentials.json:/gcp/creds.json:ro"

    ports:
      - "80:80" # Assuming your app listens on port 80
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - "$HOME/Documents/Keys/cert.pem:/app/ssl/cert.pem"
      - "$HOME/Documents/Keys/key.pem:/app/ssl/key.pem"
